### PR TITLE
New cascor

### PR DESCRIPTION
**Pull request by tksolway**
Please review, 

There are two ships that need a JS item I believe.  The Calaq has a heavy weapon that works the same as the Rutarian, it needs something to prevent it from firing both guns on the same turn.  The Tiqnicc has a rear gun that takes -2 if it fires at the same time as it's other guns.

### CODE REVIEW

**Comment by tksolway** [comment]
I don’t think the -2 is a huge deal, I say we just ignore it then.

**Comment by Zero1627** [comment]
OK. Will compile and deploy at the first moment I have an hour or two for FV coding - Monday evening at the latest.

**Comment by Zero1627** [comment]
DEPLOYED :)

**Comment by Zero1627** [comment]
I see some minor things to be fixed - am doing them in my branch, will deploy once fixes are reasonably complete.

**Pull request merged**
