### PR TITLE
Add damage types

### PR DESCRIPTION
**Pull request by tksolway**
Hey guys take a look at where I'm adding this and let me know what you think.

### CODE REVIEW

**Comment by tksolway** [comment]
Yarr, it was up to date last night when I did the work :-)  You commit monster

**Comment by tksolway** [comment]
And more learning curve :-)  Apparently I have to pull into my fort your commits before they will sync with my repository.  Makes sense when you think about it.

**Comment by AncientSion** [comment]
Ok, cool.
Now, since you made a FORK, your version of FV will NOT automaticly be kept in sync with the main project.
Forks are meant to be used like "i want to start my own project from here on aka fork" instead of "i want to contribute to *this* project".

So basicly, you can continue like you did (request the master to authorize your pull request from the fork) BUT in my eyes the better way would be to become a direct contributor to the master. 
You wouldnt have to manually sync your project and instead of requesting a pull, you could directly commit to the master (its what Jazz and i do).

Perhaps something to keep in mind for when you feel comfortable enough in altering the master directly (which comes with a risk).

**Comment by tksolway** [comment]
Yarr, I would love to work on the main fork, but Aatu has to add me as a contributor before I can do that.

**Pull request closed without merging**
