### PR TITLE
Added Civilian Ships

### LINKED ISSUE #125: Add Raider and Civilian Ships
Specifically the Felucca and Fast Freighter, there may be other SCSs that can be easily added without engine changes.

### PR DESCRIPTION
**Pull request by tksolway**
Closes #125 

These should be done, one ship is without hit chart, I built it before figuring out that the hit chart wouldn't work with it yet.  It can run with the old rules for the time being.  

Let me know if I need to make any changes.

### CODE REVIEW

**Comment by AncientSion** [comment]
Awesome, looks pretty good from a quick glimpse !

When will you draw ship icons ?

**Comment by tksolway** [comment]
Good Question, how does one do that?  I have never worked with graphics before.

**Comment by AncientSion** [comment]
It was intended to be joke, i thought you would understand it without me making a smiley :dancer: 

For graphics, i use photoshop. My very first was the Warlock, then Apollo and Delphi. Then Brakiri.
Its a real fun, creative way of participating with FV, but its also very, very time consuming.
Could you do a list for which of these vessels need new icons and which "have" icons / are alternate versions ?
Then i could copy/paste some quick things perhaps.

**Comment by tksolway** [comment]
Sure, I'll go through the list tonight and see what needs new pics.  Definitely the liner, I don't think we have anything quite like that.

**Comment by tksolway** [comment]
Here is a list

Q-Ship - Use Civ Freighter
Fast Freighter - Just shorten Civ Freighter
Luxury Liner (new image)
Tug (both Tanker and Cargo should looks about the same) (New Image)
Pirate hunter - Looks like Centauri Amar - will need to change colour and maybe blunt the spires.
Civ ore Barge (New Image) will be the same image for two others though once they are implemented.

**Pull request merged**
