### PR TITLE
Marcin sawicki targeting

### PR DESCRIPTION
**Pull request by tksolway**

### CODE REVIEW

**Comment by tksolway** [comment]
I don't see the White Star here, have you uploaded it?

**Comment by tksolway** [comment]
The changes to Shipwindow.js crash the game.  I'm not sure exactly what the issue is, but when I comment out your changes it functions properly.

**Comment by Zero1627** [comment]
most probably some typo :( . Will check.
 
W dniu 2016-04-22 04:09:32 użytkownik tksolway <notifications@github.com> napisał:
The changes to Shipwindow.js crash the game. I'm not sure exactly what the issue is, but when I comment out your changes it functions properly.
—
You are receiving this because you were assigned.
Reply to this email directly or view it on GitHub
 
 
 
 
--
*** Uwielbiam poranki! Tylko dlaczego są tak wcześnie... ***

**Comment by Zero1627** [comment]
found copy-paste error, corrected it - can retest.

**Comment by tksolway** [comment]
These changes seem to function in Chrome, although I still see the numbers before the name in the display of the hit chart.  Let's just go ahead with the numbers showing in the hit chart for now.  As it seems to function that way.  Can you build a White Star with this hit chart so I can test it before next weekend?

**Comment by Zero1627** [comment]
White Star: it's done about a week ago, I noticed You on FB and in issue thread?... 

>Let's just go ahead with the numbers showing in the hit chart for now. As it seems to function that way. 
Sure! I'll try to correct the issue with display again then...

**Comment by Zero1627** [comment]
I switched to You just so You get notified :), changing assignee back to me now.

**Comment by Zero1627** [comment]
I have simplified code (no recurency), hopefully it will work now. New fragment by itself I have tested in a separate file, works in Chrome and Firefox.

**Comment by Zero1627** [comment]
if there's still problem, can You please tell me which line is indicated?

**Comment by tksolway** [comment]
Tests good, merging.

**Pull request merged**
