### PR TITLE
Raider scs

### PR DESCRIPTION
**Pull request by tksolway**
Take a look at the example Chris.

### CODE REVIEW

**Comment by AncientSion** [comment]
So, how exactly will this work ?
We have the hitchart array in each ship, which equals with the "offical" hitchart from the SCS.
Upon being hit, instead of doing the entire "roll a dice equal to a systems HP, check, add to total, roll again rinse and repeat" you want this ? 
- get hit location by degree
- roll D20. get the string that is equal to the index of the hitchart array, where roll == index-1

Now you have a string of a systems name.
Now you loop over the ship and get each system where the displayName == string and location == hitLocation

You now have one more systems of name XYZ in your array.
You you randomly determine which system is being hit by random dice, while accounting for the ability for the system to be destroyed, and redirecting the "hit" to another system in your "targets" array ?

**Comment by tksolway** [comment]
Pretty much correct yes.  Although I am setting the indexing on each chart from 1-20 so you won't need to alter the roll at all.

**Comment by AncientSion** [comment]
Mh. Seems simple. It might also call for a small addition to the client - add a smallsish table to the FV Ship SCS where you can actually display that ships hitcharts.
It might try to implement it today for the ships you already created with the hitcharts array and make a small skirmish test. I feel like it should be easy.

Are there any special considerations to take care off for certain vessels, or is the hitchart always a D20 by stock rules.

**Comment by tksolway** [comment]
The Hitchart is always D20 as far as I know.  The only special situation might be where the hitchart refers to a specific system rather than a group of systems, and I believe we can fix that simply by giving that system a special name when we build it.

**Comment by tksolway** [comment]
Displaying the Hitchart would be a cool feature I think everyone would like :-).

**Pull request merged**
