### PR TITLE
New Weapons

### PR DESCRIPTION
**Pull request by tksolway**
Added three new weapons to support Usuuth

Marcin, I've added three new weapons (no images yet, I'll come up with some shortly).  I've added these to autoload, is there anywhere else that I need to make changes to for these weapons or should this be good?

### CODE REVIEW

**Comment by Zero1627** [comment]
You need 3 things for a system to work:
 - weapon class itself (You've obviously done that)
 - autoload entry (same)
 - javascript class (for any system that doesn't need specific front-end activities - just a placeholder really, but still necessary). 

Javascript classes are in **/public/client/model** directory, structured similarly to server side model directory. So Particle weapons should go into **/public/client/model/weapon/particle.js** file (see existing weapons for example).

One other note - when copy-paste'ing weapons it's easy to miss structure/power data of the weapon, which leads to funny situations. I've started to put default values for these attributes (as they are always the same throughout the game system), used if code calls for value 0. I found this quite convenient, especially as You don't neet to seek appropriate values on SCS for less-used weapons ;).

This means adding just a small code fragment. For Particle Hammer, You change:

function __construct($armour, $maxhealth, $powerReq, $startArc, $endArc){
            parent::__construct($armour, $maxhealth, $powerReq, $startArc, $endArc);
        }

into:

function __construct($armour, $maxhealth, $powerReq, $startArc, $endArc){
            if ( $maxhealth == 0 ) $maxhealth = 12;
            if ( $powerReq == 0 ) $powerReq = 5;
            parent::__construct($armour, $maxhealth, $powerReq, $startArc, $endArc);
        }

**Comment by Zero1627** [comment]
One more note - new interface uses very extensive cache system (that's why games load quite quickly now :) ). New ships (and changes in existing ships) won't work correctly unless ship data cache file is recompiled (and this needs local system to work). 

I can do necessary compilations on my system, but not necessary on a moment's demand.

**Comment by Zero1627** [comment]
And a final request - can You please bunch Your new autoload entries into one block near the end of the list? (like You actually did for Usuuth weapons!)

Some of the changes I will be doing in parallel will scatter changes all over the file (no easy way around that, I'll change existing things), so when merging that I'd like to just use my file with Your additions copy-pasted in.

**Comment by Zero1627** [comment]
Also, one more thing: **Light and Heavy Particle Projectors are already done and working**, You don't need to add a second copy ;) .

They're called **NexusParticleProjectorLight** and **Heavy** (because they were done for custom ships, I didn't remember official units used such weapons as well), but they are the same weapons (and their stats should match official ones).

**Comment by tksolway** [comment]
Fair enough,

I don’t have a local test system setup anymore anyway.  Are you willing to compile and test once I’ve got a branch complete?

**Comment by tksolway** [comment]
If there are the Nexus ones available I'll just use those.  Didn't notice they were the same.

**Comment by tksolway** [comment]
I've added the items to the JS and the default constructors.  

I decided to keep the official particle functions, that way if you ever need to make changes to the Nexus ones you can without affecting the others, they'll be easy to find since they are in particle as well.  I did steal the icons though :-).

**Comment by Zero1627** [comment]
>I don’t have a local test system setup anymore anyway.  Are you willing to compile and test once I’ve got a branch complete?

sure!

>I decided to keep the official particle functions, that way if you ever need to make changes to the Nexus ones you can without affecting the others

Also all right.

**Comment by tksolway** [comment]
I've added the ships as well.  You should be able to test them at the same time next week.

**Comment by Zero1627** [comment]
Tom, one more important thing (I've glanced over Your new ships): variantOf needs to be filled with shipClass value (eg. visible name), not phpclass (eg. class name).

So, for example:

base ship:
$this->shipClass = "Orthuus Battle Leader";

variant:
$this->shipClass = "Orthuul Fleet Scout"; 
$this->variantOf = "Orthuus Battle Leader";

If variantOf calls to a ship that doesn't exist, the variant will simply not be displayed (btw that's a good way to block an old design without breaking current games that use it).

**Comment by tksolway** [comment]
K, I can make those changes

**Comment by Zero1627** [comment]
checking and possibly merging - please do not make changes in this thread now

**Comment by Zero1627** [comment]
You're using usuuth and Usuuth - note that these would be displayed as two different factions

**Comment by Zero1627** [comment]
Merged.

**Pull request merged**
