### PR TITLE
Minbari update

### PR DESCRIPTION
**Pull request by tksolway**
This update includes a few new Minbari ships, as well as updates to the current ships to fit the new ship tags.  (rarity and variant etc.)

### CODE REVIEW

**Comment by Zero1627** [comment]
reviewed roughly, seems fine on a glance.

**Comment by tksolway** [comment]
Cool, can you integrate it into your next release?

**Comment by Zero1627** [comment]
I have a large project underway (second step of firing remake). I don't know whether it'll be ready any time soon. I suggest You integrate Your changes into Master and deploy (they're mostly hit charts, new units and the like), and when (...if...) my project is done I'll worry how to integrate into changed Master (there shouldn't actually be all that many files that we both change, except autoload that is).

So I'm assigning You here and in other Your updates :)

**Comment by tksolway** [comment]
Sounds fine.  Didn’t want to step on your toes since you’ve been doing all the work for the last six months ☺.

**Pull request merged**
