### PR TITLE
Added the requested hit charts

### LINKED ISSUE #130: HitLocation rewrite
In regards to finish rewriting the getHitSystem function, i require new "adjusted" SCS for non-capitals.

i need
1 each MCV, HCV, Cap from DRAZI faction,
1 each MCV, HCV from non-drazi faction,
1 misc OSAT.

Also, need to remember that the hitTable needs to contain the systems displayName.
Can you please issue one pull request for that lot ?

thanks

### PR DESCRIPTION
**Pull request by tksolway**
closes #130

### CODE REVIEW

**Comment by tksolway** [comment]
Hey Chris, this should be ready for you to test with.

**Comment by AncientSion** [comment]
Cool, thanks.
After you did this, what is your impression, is it much harder to create the arrays by typing up the ACTUAL system names and would you prefer to stick with the "old" (all lowercase, no blank spaces) version ? Both are possible, is one way considerably quicker done by you than the other (as in it is worth it to write a function that "translates" name to displayName).

**Comment by tksolway** [comment]
Lets just stick with Display name, its not too difficult.  And I've already been adding a few ships with altered systems due to hit chart requirements.  It might be difficult to translate the name to display name in that case.


________________________________

**Comment by AncientSion** [comment]
+        		1=> array(
+        				6=> "Thruster",
+        				8=> "Medium Pulse",
+        				10=> "Light Pulse",
+        				12=> "Interceptor MK I",
+        				17=> "Structure",
+        				20=> "Primary",
+        		),

just as a sidenote, Light Pulse / Medium Pulse is missing the "Cannon".
Thanks for the work.

**Comment by tksolway** [comment]
My Bad, sorry.  For some reason got it into my head that they were missing the Cannon at the end.  Hope that stuff still worked for you.


________________________________

**Pull request merged**
